### ISSUE TITLE
Issue with ESP8266 Arduino IDE board version 2.5.2

### ISSUE THREAD

**Issue by fhempy** [ximon/Hot-tub-remote#1]
Hi,

can you please add
ICACHE_RAM_ATTR
before the 2 functions which are called by the interrupt handler.
```
ICACHE_RAM_ATTR void handleButtonPress() {
  sendTestCommand = true;
}

ICACHE_RAM_ATTR void handleDataInterrupt() {
  word data = receiveCommand();
  decodeCommand(data); 
  lastReceivedCommand = millis();
}
```

Otherwise it crashes on startup, see also
https://github.com/esp8266/Arduino/issues/1734

Many thanks for your great work!

**Comment by ximon** [comment]
I've added these, still works with 2.4.2 and now compiles and runs with 2.5.2 also, will double check tonight if moving to 2.5.2 causes any issues.

**Comment by ximon** [comment]
Moving to 2.5.2 has uncovered some existing exception issues, I've rewritten the way data is read and written to completely avoid delays in the isr and use timers to check and clock the bits. Will commit after testing (tomorrow hopefully)

**Comment by ximon** [comment]
I've re-wrote the data receiving code and it's working well, just looking into abusing i2s to send data with DMA.

**Comment by ximon** [comment]
This issue is resolved
