### ISSUE TITLE
ESPHOME compatibility

### ISSUE THREAD

**Issue by jperquin** [ximon/Hot-tub-remote#2]
I am running a HASS system on RPi3b with HASSIO and ESPHOME. Mainly because ESPHOME makes managing all components so easy. I have a similar INTEX Spa (with jets and bubbles) and love to be able to use the ground work you have done (kudo's BTW) as a basis for an ESPHOME component.

My programming skills do not go beyond basic yaml, so any suggestions would be appreciated.

**Comment by ximon** [comment]
I'd check that it is the three wire model first, as the other models are quite different - there's another project for the four wire model on hackaday.io which might be worht checking out.

I am looking into adding MQTT support once i've ironed out the last few niggles.

**Comment by jcallaghan** [comment]
Do you have the link to the four-wire model, please?

**Comment by ximon** [comment]
Sure:
[Hackaday project](https://hackaday.io/project/164551-lay-z-spa-remote-control)
[Google docs info](https://docs.google.com/presentation/d/e/2PACX-1vTHQPsuV6sXKc5gxL9crg099udq97GZqN0jf2Jnf2mCJcU21wUM8zd_1vZSeGWA5wYvWniveEIPkd5f/pub?start=false&loop=false&delayms=60000)

**Comment by ximon** [comment]
I've started working on MQTT integration on this, will update when i've made progress

**Comment by jcallaghan** [comment]
This is really cool to see Simon. Great work! I have analyzed my four-wire Hawaii Hydrojet Pro and am just trying to plan my next stage to integrate using an ESP board.

**Comment by ximon** [comment]
MQTT is now part of the project, accepts commands on hottub/cmnd/* and sends out status messages on any status change on hottub/state/status

**Comment by Swiftnesses** [comment]
@jcallaghan I have a hydrojet pro, did you get this working on that model?
