### ISSUE TITLE
6 pin version

### ISSUE THREAD

**Issue by sanyatuning** [ximon/Hot-tub-remote#4]
Can anyone help me with 6 pin version: [images](https://photos.app.goo.gl/3iwWzNdyU5Ki6gqM6)
Any guess how to start?

Measured on cabels from base unit without the head:
* p1 VCC (based on photo)
* p2 GND (based on photo)
* p3 ? measured: 4.6-4-7V (pulsing, can be digital)
* p4 ? measured: 4.6-4-7V (pulsing, can be digital)
* p5 ? measured: 4.3-4.6V (pulsing, can be digital)
* p6 ? measured: 0V (no guess)

**Comment by phiberjenz** [comment]
What is the model number of your pump? I have a #54112 (Swedish market, bought last year). Haven’t opened it up yet but my guess is that it is not 3-pin...

**Comment by phiberjenz** [comment]
Nope, I have 4 pins :D

**Comment by byles** [comment]
I have 6 pins, when it stops raining I plan to stick the logic analyser on it..

**Comment by byles** [comment]
Here's a real quick capture in sigrok pulseview. 
I don't really know what I'm doing :) 
And it's still wet outside :(
[Archive.zip](https://github.com/ximon/Hot-tub-remote/files/4560407/Archive.zip)

D0 = pin 3, and so on.
D3 (pin 6) goes high when I pressed a button and it goes beeeep

**Comment by sanyatuning** [comment]
@byles this is awesome, huge thanks
I have model #54314

**Comment by byles** [comment]
I can't make any sense of that short capture if I'm honest... I will do it again properly as soon as the weather is better and at a higher sample rate. Any thoughts on what that connector is? I don't want to hack up mine :)

**Comment by sanyatuning** [comment]
mine is [SM connector](https://www.pcboard.ca/image/cache/catalog/products/connectors/jst/jst-sm/4-pin-jst-sm-pair-1-551x551.jpg)

**Comment by pdecat** [comment]
FWIW, I've got a model #54129 Palm Springs (French market bought two years ago) and it's a 4 pin.

![image](https://user-images.githubusercontent.com/318490/80920361-a659a300-8d6f-11ea-9082-de16d49f2b70.png)
![image](https://user-images.githubusercontent.com/318490/80920369-ba050980-8d6f-11ea-9a60-eb250cbbbdf0.png)

**Comment by byles** [comment]
The one I'll be poking around on is #54123 UK market. Thanks to sanyatuning, 6 pin connectors should be arriving in a few days!

**Comment by byles** [comment]
Just a thought... I've seen they have an iphone/android app for controlling these things. I wonder if the 5/6th line is for a Wi-Fi adapter of some sort on a newer/higher model.

**Comment by sanyatuning** [comment]
@byles what was the state of the hot tub when you captured this?
It was turned on?
It was filtering or heating?
What was the water temperature? (as you remember)

Thanks!

**Comment by byles** [comment]
Hey sorry didn't see the email til just now.
I'm attaching a capture from earlier today. 

Pin 6 is just the beep, if it's disconnected, there's no beep!

I didn't seem to get any data at all on 3,4 or 5 from the control panel when the control panel was disconnected, maybe it only sends in response to messages from pump during the gap or when polled. master/slave?

3,4 and 5 always have data sending from pump regardless of control panel being connected.

State of machine during this capture:

On
Unlocked
No timer
Bubbles Off
Filter On
Heat On (green - standby/not heating)
35℃ 

[hottub2.zip](https://github.com/ximon/Hot-tub-remote/files/4583510/hottub2.zip)

Would I be daft to think this is SPI, D0 (line 3) data, D1 Clock, D2 Chip select. 24us bits time

**Comment by sanyatuning** [comment]
may be correct

this short message is repeating
![image](https://user-images.githubusercontent.com/2077907/81198247-8b7e6d00-8fc1-11ea-9e83-46a316dc9a9a.png)

sometimes there is a longer message
![Screenshot from 2020-05-06 17-50-10](https://user-images.githubusercontent.com/2077907/81198764-2414ed00-8fc2-11ea-9628-3de6221228ac.png)

**Comment by byles** [comment]
I wanted to share this before I get into it; I've taken some data with various settings.
Sorry I decoded it as LSB first, we can always change it later.


C0 01 FE 9F FE 0F FE 29 FF F7 FF    37c     heat on     filter on   bubbles off     lock off
C0 01 FE 9F FE 0F FE 21 FF F7 FF    37c     heat on     filter on   bubbles off     lock off
C0 01 FE 9F FE 0F FE 21 FF F7 FF    37c     heat on     filter on   bubbles off     lock off
C0 01 FE 9F FE 0F FE 01 FF F7 FF    37c     heat off    filter on   bubbles off     lock off
C0 01 FE 9F FE 0F FE 01 FF F5 FF    37c     heat off    filter off  bubbles off     lock off
C0 01 FE 9F FE FF FE 21 FF F7 FF    38c     heat on     filter on   bubbles off     lock off
C0 01 FE 9F FE FF FE 41 FF F7 FF    38c     heat stdby  filter on   bubbles off     lock off
C0 0D FE 7F FE 7F FE 21 FF FB FF    100f    heat on     filter on   bubbles off     lock off
C0 01 FE 9F FE FF FE A1 FF F7 FF    38c     heat on     filter on   bubbles on      lock off
C0 01 FE 9F FE FF FE 01 FF E5 FF    38c     heat off    filter off  bubbles off     lock off    -- power off
C0 01 FE 9F FE FF FE 81 FF F7 FF    38c     heat off    filter on   bubbles on      lock off
C0 01 FE 9F FE FF FE 81 FF F5 FF    38c     heat off    filter off  bubbles on      lock off
C0 01 FE 9F FE FF FE 29 FF F7 FF    38c     heat on     filter on   bubbles off     lock on
C0 01 FE 9F FE FF FE 01 FF F5 FF    38c     heat off    filter off  bubbles off     lock off

"01H" / "38" - timer on, alternating display
C0 7F FE 0D FE ED FE 35 FF F7 FF    01H
C0 01 FE 9F FE FF FE 35 FF F7 FF    38c

**Comment by byles** [comment]
https://docs.google.com/spreadsheets/d/1mqK0INE1kh0g_M_HerP3LNWXHpvr-ZIPXr-yXfrYt_k/edit?usp=sharing

Sorry, I went LSB first 🙄

**Comment by sanyatuning** [comment]
I am using lib [SPISlave](https://github.com/esp8266/Arduino/blob/master/libraries/SPISlave/examples/SPISlave_Test/SPISlave_Test.ino
) with esphome on a wemos d1 mini
and I got this:
```
[19:51:00][D][HotTub:018]: D8.C1.FE.03.FE.9F.90.FF.AF.FF.11.D8.D8.42.D8.D8.42.D8.D8.42.D8.D8.80.02.03.80.7F.B0.7F.F0.7F.80 (32)
```

**Comment by byles** [comment]
So that looks the same as in my spreadsheet, more or less. You have bubbles and heat on?

All mine started C0 so I wonder what C1 is. What state was yours in? 

Should I flip the data in my spreadsheet to be msb first? If you want to request edit and add to it feel free.

**Comment by sanyatuning** [comment]
fully off or standby
I will capture some data in all states soon

**Comment by byles** [comment]
Well, I wouldn't capture any data if it was fully off 😁 

Standby, when screen is dim and not running.

**Comment by sanyatuning** [comment]
How you capture the data?

**Comment by byles** [comment]
![IMG_20200505_2006552](https://user-images.githubusercontent.com/1180108/81381539-cf2dbf80-9104-11ea-9287-ac78e7fcd2fb.jpg)

Cheap logic analyser from Amazon and sigrok. Capturing at 250Hz just so I didn't miss anything. When it was slower sample rate, that clock line wasn't so obviously a clock.

Made jump wires with the SM connectors you identified.

**Comment by sanyatuning** [comment]
Can you please share a new capture file?

**Comment by byles** [comment]
The hottub2.zip above is the last one Ive done, is what makes up spreadsheet :)

**Comment by sanyatuning** [comment]
@byles I wrote a code what reads the current state of the spa.
It is an esphome custom component running on a esp8266.

**Comment by byles** [comment]
@sanyatuning nice, would be good to see what you've got. I was busy this weekend so wasn't able to get anything more done yet.

**Comment by sanyatuning** [comment]
@byles https://github.com/sanyatuning/hot-tub

**Comment by chunkysteveo** [comment]
I have a 4 pin model like @phiberjenz  - would love to get some remote monitoring and management of the 'Tub. Great work so far guys - i'm very interested in this project. Is the 4 pin going to be different to the 6 pin do you think, SPI, I2C?  - V, G, D, C?? has anyone probed the 4-pin version?

**Comment by reevery** [comment]
I've also got a four pin version and have ordered some kit to start probing that. Model 54156. Not entirely sure what I'm doing, but will figure it out.

**Comment by chunkysteveo** [comment]
Haha good! Keep me posted @reevery ! I suspect the lines are clock and data, and it would just be a case of reversing the protocol and copying. But I've literally no idea!! Would give me an excuse to buy a logic analyser. Was a pain walking to the bottom of the garden today to turn the heater on.... lol #firstworldproblems 😂

**Comment by chunkysteveo** [comment]
Found this guys who has a diy product for sale, and uses the 4-pin model too - https://hottubmanager.co.uk/ Only has monitoring states, but surely just need to add in a sending module to the mix to add in the controls? Looks promising too!

**Comment by reevery** [comment]
I have finally got round to recording data from the 4-pin.

Pins 1-4 are: vcc, signal 1, signal 2, gnd.
Starts with pump on, heat on, air off. Temp would have been early 30s centigrade. Then heat off, pump off, pump on, heat on, air on, air off, and I think air cycles again.

I really don't know what I'm looking at though.

Data is [here](https://drive.google.com/file/d/1oFCLdTXhxz-6oxqCB74gCrj8YP5WzXa-/view?usp=sharing).

**Comment by chunkysteveo** [comment]
Cool! Nice work - hope someone can work with it?!

**Comment by reevery** [comment]
I've been trying to make some headway but am struggling a little with direction.

From what I can work out, the 6-pin uses SPI, but I think @ximon yours is UART. Is the 74LVC1T45 then just to split your input and output out? If so, with a signal in and out line on the 4-pin I imagine I don't need this component. What was your baud rate? This is 9600 on mine - does it look similar?
![image](https://user-images.githubusercontent.com/4381067/84591091-8ec40e80-ae33-11ea-9767-e64b1d44aeb3.png)

If that is the case, then my suspicion is that I can use your code but wiring directly to the ESP.

Would the capacitor be needed in all situations and if so where is it wired in? Is it literally just across VCC and GND of the ESP?

Then the next problem is figuring out how to write the code to the Wemos. I know you posted this link (am copying here for my info mainly): https://averagemaker.com/2018/03/wemos-d1-mini-setup.html

**Comment by ximon** [comment]
The hot tub i have uses a three wire cable between the display/buttons and the controller. It uses some odd protocol that i'm not familiar with - dont think it would work with UART due to the really long start pulse in comparison to the rest of the bits - It looks quite a bit different to the images above, yours won't need the 74LVC1T45 - i only needed it due to the DMA hack I'm using to send out the data.

The big capacitor is just a buffer for when the pump and blower motors turn on - It's directly across the supply.

**Comment by chunkysteveo** [comment]
Hi @reevery  - I'm going to guess that the protocol is I2C for the 4 pin version. Looks like the 7 step I2C message. If it is, we may need an I2C level shifter board for the ESP to read and write back. Although if those signals are from the two data lines, then there's no clock signal - so could well be asynchronous serial communication, like UART. Hmmm?!!?

**Comment by reevery** [comment]
Thanks @chunkysteveo! There's definitely only two signal wires. pdecat's picture above https://github.com/ximon/Hot-tub-remote/issues/4#issuecomment-623143621 shows Vcc and Gnd on the outer wires. I'm banking on UART but I will investigate it as I2C when I get a chance.

I'm struggling to configure the Wemos at present. It appears their website is kerplunk and I haven't yet found a mirror for it. Baby steps...

**Comment by eddcaton** [comment]
Looks like I have the 6 pin version as well 😭 doesn’t anyone have an update on this?

Edd

**Comment by ximon** [comment]
If we can make the control code generic enough then we should be able to just #include the relevant control code for each model, I'll take a look at doing this for the current code - 3 pin model.

Can anyone share the missing info for the other pumps?

I've collated all the information above, with pinouts, in Models.md

Thanks Guys!

**Comment by chunkysteveo** [comment]
LOVE this idea. Being able to define model number at the start of the script to compile is brilliant. Here's mine:

Model No: 54154
PinCount: 4 (Vcc, Data, Data, Gnd)
Model Name: ? From a 'Paris' Tub
Date:  2018?
Country: UK
Comments: Dark-blue/grey, Oval display. Buttons: On/Off, Lock, Timer, Bubbles, °C/°F, Heat, Filter, Temp Down, Temp Up

**Comment by 877dev** [comment]
Hi guys, very excited to see this project, as I just got a new Vegas Lay Z Spa (6 wires). I'm in the UK.

I already have a logic analyser, and have used it to interface with my Accenta alarm panel to create a "virtual" keypad on my phone. (I need to update my github to include that).

Looks like I need some 6pin SM connectors so I can get sniffing!

**Comment by der-moep** [comment]
Model No. | PinCount | Protocol | Model Name | Date | Country | Colour | Comments
54123 | 4 | -- | Miami | 2018 | Germany | Grey | Round display
54174 | 6 | -- | Honolulu | 2020 | Germany | Grey | Round display

**Comment by ximon** [comment]
> Model No. | PinCount | Protocol | Model Name | Date | Country | Colour | Comments
> 54123 | 4 | -- | Miami | 2018 | Germany | Grey | Round display
> 54174 | 6 | -- | Honolulu | 2020 | Germany | Grey | Round display

Thanks! I've added these to the main list.

**Comment by 877dev** [comment]
Model No. | PinCount | Protocol | Model Name | Date | Country | Colour | Comments
54112        |    6           |   SPI ?     |     Vegas        | 2020 |     UK     |    Grey  | Round display

**Comment by ximon** [comment]
> Model No. | PinCount | Protocol | Model Name | Date | Country | Colour | Comments
> 54112 | 6 | SPI ? | Vegas | 2020 | UK | Grey | Round display

Thanks! I've added this to the main list.

**Comment by Friseurazubi** [comment]
Here is the next model ;)

Model | PinCount | Protocol | Name | Date | Country | Colour | Comm
54173 | 4 | ? | Maldives HydrojetPro | 2020 | Germany | Grey | 2 WaterPump

Hawaii HydrojetPro should have the same controller.


![635AE1B9-9F31-4564-A170-B86154F2FFB0](https://user-images.githubusercontent.com/69161897/89213515-7ff11100-d5c5-11ea-8103-f56ee6d7b3cd.jpeg)
![4BE7C954-E57F-438E-9D4C-4C8D2478AC20](https://user-images.githubusercontent.com/69161897/89213520-81bad480-d5c5-11ea-91a0-bc8e99e5b866.jpeg)
![1E4C1212-63B1-4C73-9EC9-A48F38E64053](https://user-images.githubusercontent.com/69161897/89213551-8b443c80-d5c5-11ea-9c1e-43d20f58e5dd.jpeg)

**Comment by danjunx** [comment]
Love this idea! Really interesting in helping out if I can. 
I've got 2 Vegas model spas here, one is older than the other by a couple of years, however the internals of the pump "egg" are identical bar some different PCB rev numbers, they have the same model numbers. 

I've been doing a bit of googling around and found this project among a few others specifically for the 4 pin version - according to this document, it's using UART, and I can confirm that. [link](https://docs.google.com/presentation/d/e/2PACX-1vTHQPsuV6sXKc5gxL9crg099udq97GZqN0jf2Jnf2mCJcU21wUM8zd_1vZSeGWA5wYvWniveEIPkd5f/pub?start=false&loop=false&delayms=3000&slide=id.g4e2b8ff413_0_0)

Following the bit pattern settings on the above document, I was able to hook into the TX/RX sides and sniff the traffic from the control panel/display to the controller unit and see the data being sent between them both. Was not able to sniff the data going the other direction for whatever reason. 
I can provide some direct dumps of the serial output from the control panel/display while going through the various functions if required.

Regarding the model number of the pump "eggs" I have and their details:

Model No. | PinCount | Protocol | Model Name | Date | Country | Colour | Comments
54112 | 4 | UART | Vegas | 2015 | UK | Grey | round display, lock/timer/pump/C-F/heater/bubbles/temp up/down, one has a "test" button in place of the power button. 

Am curious about the 2 PROG headers on the boards, may be worth trying to dabble with them although I definitely don't have kit to do so at the moment - it looks like there's replacement controller boards for relatively cheap on ebay (at least here in the UK!) and I was tempted to pick one up to dabble with instead of working with my spare pump.

Couple of photos below, note the pinout of the white 4 pin display connector down the bottom left of the board, also the PROG2 header. 

![IMG_20200806_140302](https://user-images.githubusercontent.com/38396423/89739127-e66aa900-da75-11ea-8b4c-ee350633b538.jpg)
![IMG_20200806_141954](https://user-images.githubusercontent.com/38396423/89739129-e8346c80-da75-11ea-9140-0807563503e3.jpg)

**Comment by chunkysteveo** [comment]
That link is fascinating reading. Need to look into the links to their software etc. Not sure why they have an extra blower button though? Good find though!

**Comment by faboaic** [comment]
You all know this one ?
That's what I will try with my lay-z-spa Miami.

https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA

**Comment by chunkysteveo** [comment]
That's a great find too!

**Comment by ricoghardforth** [comment]
Is anyone getting anywhere with a four wire version for a esp2866 solution.  Thanks

**Comment by pejov74** [comment]
> Is anyone getting anywhere with a four wire version for a esp2866 solution. Thanks

Im also looking for a four wire version for a esp2866 solution.

**Comment by markgdev** [comment]
I've been having a look at this based on the link above, I'm hoping to have a basic setup to test in the next few days. Assuming the comms between the display and controller match for my model 🤞

**Comment by ximon** [comment]
Not much progress on this lately as my tub's pump shaft has snapped and its dismantled for the time being :(

I'm quite happy to chip in and help with anything though.

**Comment by TimE90** [comment]
Did anyone figure out the 4 pin models? Mine is a Lay Z Palm Springs and has four wires. Seems like V, GND and two data’s.
![Uploading D11F6C71-D560-4638-927C-AB089E7056A3.png…]()

**Comment by markgdev** [comment]
@TimE90, I’ve finally got a prototype running today. I’ve had to loose the ability to control through the top panel as there is no way to feedback to it that I can find other than the temp. I have kept the blower button active though and this overrides whatever is set remotely.
I will clean up my code and get some details together in the next couple of days and post on here.

**Comment by TimE90** [comment]
@markgdev congratulations this sounds pretty good! I‘m looking forward to your updates 👍

**Comment by markgdev** [comment]
As promised, I've put some details together here: https://github.com/markgdev/layzspa_remote It's still very much a work in progress but the hot tub as been running for the last couple of days now so looks promising.

**Comment by sanyatuning** [comment]
@markgdev this looks promising! Thanks for the share!

**Comment by obalthaz** [comment]
> As promised, I've put some details together here: https://github.com/markgdev/layzspa_remote It's still very much a work in progress but the hot tub as been running for the last couple of days now so looks promising.

hello, I tested yesterday on my spa, everything works as described.  thank you so much

**Comment by jenswalit** [comment]
Hello. I have an 4Pin Lay Z Spa Vegas. I will use your project. Can you say the pin out are the same as yours? Pump No 54112. thank you

**Comment by sanyatuning** [comment]
Finally this worked for me: https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA
but be careful some pins always pulled up/down and cant be used with level shifters
